### ISSUE TITLE
Integrating the Unity executable in the givery/codecheck Docker image to codecheck

### ISSUE THREAD

**Issue by holycattle** [code-check/env-builder#43]
So I created an executable in the `givery/codecheck` Docker image called `xvfb-unity`, which expects two arguments: 1) path to the repository and 2) name of the class that contains the unit test, i.e.:

``` shell
#!/bin/bash
xvfb-run /opt/Unity/Editor/Unity -batchmode -nographics -logFile -quit -projectPath $1 -executeMethod $2
```

Is that fine? I'm not sure how to integrate this into codecheck, such that you can do something like `codecheck unity` (kinda like `codecheck mocha`).

(I had already done the setting up in the existing givery/codecheck Docker image, so all I have to do now is to push this to Givery's Docker hub.)

review me @takayukioda
fyi @shunjikonishi

**Comment by takayukioda** [comment]
Awsome!!
BTW, how did you create that image?
By editing Dockerfile or by commiting?
If you made that docker image by commiting, I want you to write it down to Dockerfile so I could trace what you did and ansiblize it.
I think you could get command histories by restart old container and attach it.

Let me know whenever you have any questions / suggestions ;)

**Comment by takayukioda** [comment]
Closing this issue
