### ISSUE TITLE
export PRIVATE_KEY_PATH doesn't work

### ISSUE THREAD

**Issue by maximum80** [code-check/env-builder#6]
I've tried to export PRIVATE_KEY_PATH in ~/.ssh/id_rsa by using following README.md like that

```
export PRIVATE_KEY_PATH=~/.ssh/id_rsa
```

And then I ran amsible-playbook after set PRIVATE_KEY_PATH again.
But it doesn't work and I couldn't clone git repository.
In my opinion, the setting of amsible might be wrong and I want you to check the setting around git.
It goes well when I ran amsible by using following command

```
PRIVATE_KEY_PATH=~/.ssh/id_rsa ansible-playbook all.yml
```

Thanks,
Max

**Comment by shunjikonishi** [comment]
@maximum80 
Above two commands has same meaning.
Before run ansible-playbook, all you need is setting PRIVATE_KEY_PATH environment variable.

Though I don't know why export didn't work, at least it is not wrong.
