### ISSUE TITLE
installing nuget cli tool

### ISSUE THREAD

**Issue by takayukioda** [code-check/env-builder#93]
Currently codecheck does not have a way to do nuget package installing.

At least, we know following command enables user to use nuget.
Find out efficient and official way to install nuget cli tool and its cache directory.

```sh-session
$ wget --no-check-certificate https://nuget.org/nuget.exe
mono nuget.exe install Nancy
```

Add this installation on Dockerfile.

**Comment by sukeshni** [comment]
@takayukioda Should I specify the version of `nuget` and `Nancy` or by default latest version should be installed?

**Comment by bschwind** [comment]
> Should I specify the version of nuget and Nancy or by default latest version should be installed?

Just my opinion but you should version everything you can so builds are more reproducible.

**Comment by sukeshni** [comment]
Yes I agree with you. I remember we had some issue before where version was not specified.

**Comment by TsubasaK111** [comment]
fixed, merged!
